export {default as ManageRoom } from "./ManageRoom";
export {default as AdminMaster } from "./Master";
export {default as CreateExam } from "./CreateExam";
export {default as ManageStudent } from "./ManageStudent";
export {default as ClassDetail } from "./ClassDetail";
export {default as AdminStudent } from "./AdminStudent";
export {default as ListTest } from "./ListTest";
export {default as ViewStudentProgress } from "./ViewProgress";
export {default as ReviewTest } from "./ReviewTest";